[package]
name = "bevy-codex"
version = "0.6.2"
description = "A manager for menus and huds with the bevy game engine"
repository = "https://github.com/KyleWinston/bevy-codex"
license = "MIT OR Apache-2.0"
edition = "2021"
publish = true
keywords = ["bevy", "menus", "ui"]
exclude = ["/examples"]

[dependencies]
serde = { version = "1.0.99", features = ["derive"] }
bevy = { version = "0.15.0", default-features = false, features = [
    "bevy_asset",
    "bevy_state",
    "png",
] }
bevy_easy_config = "0.2.0"
# bevy_tweening = { git = "https://github.com/SergioRibera/bevy_tweening", branch = "infinite_mirrored" }
bevy_hui = "0.2"
# bevy_hui = { path = "../bevy_hui/crates/bevy_hui" }
unicode-segmentation = "1.12.0"

[dev-dependencies]
bevy = { version = "0.15.0", default-features = false, features = [
    "bevy_asset",
    "bevy_state",
    "bevy_render",
    "file_watcher",
    "multi_threaded",
    "default_font",
    "png",
] }
cargo-husky = { version = "1", features = [
    "precommit-hook",
    "run-cargo-test",
    "run-cargo-clippy",
] }

[target.'cfg(target_os = "linux")'.dependencies.bevy]
features = ["x11", "wayland", "bevy_winit"]
version = "0.15.0"
default-features = false


# Enable a small amount of optimization in debug mode
[profile.dev]
opt-level = 1

# Enable high optimizations for dependencies (incl. Bevy), but not for our code:
[profile.dev.package."*"]
opt-level = 3

[profile.release]
codegen-units = 1
strip = true

[package.metadata.android.sdk]
target_sdk_version = 34
min_sdk_version = 33
