[package]
name = "bevy-codex"
version = "0.6.2"
description = "A manager for menus and huds with the bevy game engine"
repository = "https://github.com/KyleWinston/bevy-codex"
license = "MIT OR Apache-2.0"
edition = "2021"
publish = true
keywords = ["bevy", "menus", "ui"]
exclude = ["assets/**/*", "tools/**/*", "examples/**/*", ".github/**/*"]


[dependencies]
serde = { version = "1.0.99", features = ["derive"] }
bevy = { version = "0.15.2", default-features = false, features = [
    "bevy_asset",
    "bevy_state",
    "bevy_text",
    "bevy_render",
    "bevy_window",
    "png",
] }
bevy_hui = "0.2.1"
bevy_yarnspinner = { git = "https://github.com/wiggleforlife/YarnSpinner-Rust", branch = "main" }
unicode-segmentation = "1.12.0"
bevy_hui_widgets = "0.1.0"

[dev-dependencies]
bevy = { version = "0.15.2", default-features = false, features = [
    "bevy_render",
    "file_watcher",
    "multi_threaded",
    "default_font",
    "bevy_remote",
    "tonemapping_luts",
] }


[target.'cfg(target_os = "linux")'.dev-dependencies.bevy]
features = ["x11", "wayland", "bevy_winit"]
version = "0.15.2"
default-features = false


# Enable a small amount of optimization in debug mode
[profile.dev]
opt-level = 1

# Enable high optimizations for dependencies (incl. Bevy), but not for our code:
[profile.dev.package."*"]
opt-level = 3

[profile.release]
codegen-units = 1
strip = true

[package.metadata.android.sdk]
target_sdk_version = 34
min_sdk_version = 33
