[package]
name = "bevy-codex"
version = "0.5.13"
description = "A manager for menus and huds with the bevy game engine"
repository = "https://github.com/KyleWinston/bevy-codex"
license = "MIT OR Apache-2.0"
edition = "2021"
publish = true

keywords = ["bevy", "menus", "ui"]
# exclude = ["/examples"]

[dependencies]
serde = "1.0.99"
bevy = { version = "0.14.0", default-features = false, features = [
    "bevy_asset",
    "bevy_state",
    "bevy_winit",
    "bevy_render",
    "bevy_core_pipeline",
    "bevy_sprite",
    "bevy_ui",
    "x11",
    "png",
    "asset_processor",
    "accesskit_unix",
] }
bevy-settings = "0.6.0"
bevy_third_person_camera = "0.1.11"
bevy_common_assets = { version = "0.11.0", features = ["toml"] }
async-executor = "1.12.0"
bevy_lunex = "0.2.2"
